project:
  type: book
  output-dir: "../"

book:
  title: "An Analysis of Educational Diagnostic Questions"
  author:
    - "Bhavana Jonnalagadda"
    - "Erik Whitfield"
  chapters:
    - index.qmd
    - intro.qmd
    - methods.qmd
    - results.qmd
    - conclusions.qmd
  downloads: [pdf]
  output-file: CSCI_5502_Final_Report # PDF filename
  # cover-image: cover.png # Do we need a cover?
  repo-url: "https://github.com/CUBoulder-DS/CSCI-5502-Final-Report"
  page-navigation: true
  navbar:
    pinned: true

bibliography: references.bib
# Force all refs in .bib file to appear in References
nocite: |
  @*

format:
  # html:
  #   theme: flatly
  #   page-layout: full
  #   smooth-scroll: true
  #   number-sections: true
  #   citations-hover: true
  #   grid:
  #     body-width: 1000px
  #     sidebar-width: 150px

  pdf:
    documentclass: scrreprt
    number-depth: 4
    toc: true
    link-citations: true
    csl: apa.csl
    header-includes: # dont need?
      - \usepackage{float}
      - \floatplacement{table}{H}
      - \floatplacement{image}{H}
    hyperrefoptions:
      - linktoc=all
    latex-output-dir: "../"
    geometry:
      - margin=0.5in
    fig-pos: "H"

## Extra settings

# Don't include code in the report
execute:
  echo: false
  warning: false
  error: false
  freeze: auto

latex-clean: true # delete latex files after rendering
latex-auto-mk: true
latex-auto-install: true
