project:
  type: book
  output-dir: "../"

book:
  title: "An Analysis of Machine Learning on Educational Data"
  author:
    - "Bhavana Jonnalagadda"
    - "Erik Whitfield"
  chapters:
    - index.qmd
    - intro.qmd
    - data.qmd
    - methods.qmd
    - results.qmd
    - conclusions.qmd
    - references.qmd
  downloads: [pdf]
  output-file: CSCI_5502_Final_Report # PDF filename
  # cover-image: cover.png # Do we need a cover?
  repo-url: "https://github.com/CUBoulder-DS/CSCI-5502-Final-Report"
  page-navigation: true
  navbar:
    pinned: true

bibliography: references.bib

format:
  # html:
  #   theme: flatly
  #   page-layout: full
  #   smooth-scroll: true
  #   number-sections: true
  #   citations-hover: true
  pdf:
    documentclass: scrreprt
    number-depth: 4
    toc: true
    link-citations: true
    csl: apa.csl
    # header-includes: # dont need?
    #   - \usepackage{float}
    #   - \floatplacement{table}{H}
    #   - \floatplacement{image}{H}
    geometry:
      - margin=0.5in

## Extra settings

# Don't include code in the report
execute:
  echo: false
  freeze: auto

latex-clean: true # delete latex files after rendering
latex-auto-mk: true